### ISSUE TITLE
Sharing URL with # data.

### ISSUE THREAD

**Issue by chopfitzroy** [ritz078/socialShare.js#6]
Hey when I share pages I want to include the # data in example if I share currently I get this:

http://example.com/some/url

But what I want is this:

http://example.com/some/url#-JyqKOu8s6Qt6RkTA-qI

Cheers,
Otis.

**Comment by ritz078** [comment]
Hi,
if there's `#` in the link of the page, it should send it because i am using `window.location.href` which automatically includes the hash. If you are making something using Angular or similar frameworks, the url may not be updating because the plugin isn't called after the url has been changed and still the old url is used.

**Comment by chopfitzroy** [comment]
Oh okay that clears that up :) thank you
